# Generated by Django 5.1.3 on 2024-11-25 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_message_with_admin_message_with_dev'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Notdone', 'Notdone'), ('Confirm', 'Confirm')], default='Notdone', max_length=7),
        ),
    ]
